"""empty message

Revision ID: 08497592847f
Revises: 
Create Date: 2025-11-03 15:40:51.399903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '08497592847f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_scraped_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('data_source_id'),
    if_not_exists=True
    )
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    if_not_exists=True
    )
    op.create_index('idx_locations_geo_boundary', 'locations', ['geo_boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    if_not_exists=True
    )
    op.create_table('listings',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('listing_id'),
    if_not_exists=True
    )
    op.create_table('metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('metric_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('effective_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='TRUE', nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.data_source_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    if_not_exists=True
    )
    op.create_table('user_preferences',
    sa.Column('preferences_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_rooms', sa.Integer(), nullable=True),
    sa.Column('preferred_region_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['preferred_region_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preferences_id'),
    if_not_exists=True
    )
    op.create_table('favorite_listings',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_user_listing'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS postgis;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_listings')
    op.drop_table('user_preferences')
    op.drop_table('metrics')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_index('idx_locations_geo_boundary', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
