"""add fields

Revision ID: 68173225a69b
Revises: 77f08563e2a2
Create Date: 2025-12-21 15:41:19.300400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68173225a69b'
down_revision: Union[str, Sequence[str], None] = '77f08563e2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('floor', sa.String(length=64), nullable=True))
    op.add_column('listings', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('complex', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'complex')
    op.drop_column('listings', 'year_built')
    op.drop_column('listings', 'floor')
    # ### end Alembic commands ###
