"""empty message

Revision ID: a81a342260a9
Revises: 48e2da53094c
Create Date: 2025-11-03 16:30:14.596224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a81a342260a9'
down_revision: Union[str, Sequence[str], None] = '48e2da53094c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    op.drop_constraint("favorite_listings_user_id_fkey", "favorite_listings", type_="foreignkey")
    op.drop_constraint("user_preferences_user_id_fkey", "user_preferences", type_="foreignkey")

    op.alter_column("users", "user_id", new_column_name="id")

    # op.drop_constraint("users_pkey", "users", type_="primary")
    # op.create_primary_key("users_pkey", "users", ["id"])

    op.create_foreign_key(
        "favorite_listings_user_id_fkey",
        "favorite_listings",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_preferences_user_id_fkey",
        "user_preferences",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("favorite_listings_user_id_fkey", "favorite_listings", type_="foreignkey")
    op.drop_constraint("user_preferences_user_id_fkey", "user_preferences", type_="foreignkey")

    op.alter_column("users", "id", new_column_name="user_id")

    op.create_foreign_key(
        "favorite_listings_user_id_fkey",
        "favorite_listings",
        "users",
        ["user_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        "user_preferences_user_id_fkey",
        "user_preferences",
        "users",
        ["user_id"],
        ["user_id"],
    )

        # ### end Alembic commands ###
