"""empty message

Revision ID: d89748402d9f
Revises: 72be85915844
Create Date: 2025-12-21 04:21:08.023463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89748402d9f'
down_revision: Union[str, Sequence[str], None] = '72be85915844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('external_id', sa.String(length=32), nullable=False))
    op.add_column('listings', sa.Column('area', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'listings', ['external_id'])
    op.drop_column('listings', 'property_type')
    op.add_column('locations', sa.Column('address', sa.String(length=512), nullable=False))
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('idx_locations_geo_boundary'), table_name='locations', postgresql_using='gist')
    op.create_unique_constraint('uq_location_geo', 'locations', ['city', 'latitude', 'longitude'])
    op.create_unique_constraint(None, 'locations', ['address'])
    op.drop_column('locations', 'postal_code')
    op.drop_column('locations', 'geo_boundary')
    op.drop_column('locations', 'state')
    op.add_column('metrics', sa.Column('agent_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'agent_name')
    op.add_column('locations', sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('geo_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('postal_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint('uq_location_geo', 'locations', type_='unique')
    op.create_index(op.f('idx_locations_geo_boundary'), 'locations', ['geo_boundary'], unique=False, postgresql_using='gist')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('locations', 'address')
    op.add_column('listings', sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'listings', type_='unique')
    op.drop_column('listings', 'area')
    op.drop_column('listings', 'external_id')
    # ### end Alembic commands ###
